import json


datas = {
    "count": 0, 
    "difficult": {
        "very-easy": 0, 
        "easy": 0, 
        "same": 0, 
        "difficult": 0, 
        "very-difficult": 0, 
    }, 
    "language": {
        "C": 0, 
        "C++": 0, 
        "Java": 0, 
        "Python": 0, 
        "C#": 0, 
        "Go": 0, 
        "JavaScript": 0, 
        "TypeScript": 0, 
        "VisualBasic": 0, 
        "Julia": 0, 
        "VBScript": 0, 
        "F#": 0, 
        "PHP": 0, 
        "Pascal": 0, 
        "Haskell": 0, 
        "Swift": 0, 
        "Ruby": 0, 
        "Perl": 0, 
        "Lua": 0, 
        "Scala": 0, 
        "R": 0, 
        "Kotlin": 0, 
        "Other": 0, 
    }, 
    "refactoring": {
        "none": 0, 
        "little": 0, 
        "less": 0, 
        "have": 0, 
        "more": 0, 
        "lot": 0, 
        "full": 0, 
    }, 
    "algorithm": {
        "never": 0, 
        "hardly-ever": 0, 
        "sometimes": 0, 
        "usually": 0, 
        "always": 0, 
    }, 
    "what-to-do": {
        "games": 0, 
        "tools": 0, 
        "websites-fore": 0, 
        "websites-back": 0, 
        "servers": 0, 
        "datas": 0, 
        "science": 0, 
        "math": 0, 
        "softwares": 0, 
        "systems": 0, 
        "algorithms": 0, 
        "languages": 0, 
        "hobby": 0, 
        "work": 0, 
        "other": 0, 
    }, 
    "uid": [], 
    "say": [], 
}

with open("submitdata.json", "w") as file:
    file.write(json.dumps(datas, indent=4))
